### ISSUE TITLE
File.inc and tempnam() on GAE

### ISSUE THREAD

**Issue by rpeace42** [boombatower/drupal-appengine#1]
I'm looking to complete the great work you've started by adding CloudStorage support but I'd like to see if anyone else is working on default file system issues like:

Warning: mkdir(): Function not implemented in drupal_mkdir() (line 2336 of /base/data/home/apps/s~[project]/1.369551769172930134/includes/file.inc).

Public files-
The directory sites/default/files does not exist and could not be created.

Temp Files -
The directory gs://[project]-drupal/sites/default/files/tmp exists but is not writable and could not be made writable.

I think tempnam() issues seen in modules could be fixed by replacing the disabled function with pure php. A friend suggested:

$tempnam = function($directory, $prefix) {
   $chars = array_merge(
       range('a', 'z'),
       range('A', 'Z'),
       range (0, 9)
   );
   $charsSize = count($chars) - 1;

   $filename = $directory . DIRECTORY_SEPARATOR . $prefix;
   for ($i = 0; $i < 4; ++$i)
       $filename .= $chars[mt_rand(0, $charsSize)];

   while (file_exists($filename) !== FALSE)
       $filename .= $chars[mt_rand(0, $charsSize)];

   return $filename;
};

**Comment by boombatower** [comment]
I have actually done a bunch of work on seamless cloud storage integration and mail handling which I hope to publish soon. I am also working with the app engine team to resolve some of the remaining issues before I publish.

**Comment by rpeace42** [comment]
Excellent. Then I will stand down unless there's some way I can contribute.

On Sun, Aug 18, 2013 at 5:09 AM, Jimmy Berry notifications@github.comwrote:

> I have actually done a bunch of work on seamless cloud storage integration
> and mail handling which I hope to publish soon. I am also working with the
> app engine team to resolve some of the remaining issues before I publish.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/boombatower/drupal-appengine/issues/1#issuecomment-22828689
> .

## 

Roderick Peace
http://www.linkedin.com/in/rjpeace
Cell 310-529-9716

**Comment by rpeace42** [comment]
anything I can do to help?

**Comment by boombatower** [comment]
Published https://drupal.org/project/google_appengine which contains GCS integration. I will have a detail blog post upcoming, but the README.txt contains a good amount of detail for now. I had to wait to get some internal issues resolved so this took longer to publish than I anticipated. Let me know if you have any issues.

This repo has also been updated and rebased on latest 7.x core branch.
